config/routes.rb
Rails.application.routes.draw do
  root :to => 'subscriptions#index'
  resources :subscriptions
  resources :sbubscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sbubscription.rb
class Sbubscription < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord

    def save_with_payment(token)
        if valid?
            customer = Stripe::Customer.create({
            source: token,
            email: "ammad.fareed@teknuk.com"
            })
            charge = Stripe::Charge.create({
            amount: 500,
            currency: "usd",
            customer: customer.id,
            description: "My First Test Charge (created for API docs)"
            })
            save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sbubscriptions_controller.rb
class SbubscriptionsController < ApplicationController
  before_action :set_sbubscription, only: [:show, :edit, :update, :destroy]

  # GET /sbubscriptions
  # GET /sbubscriptions.json
  def index
    @sbubscriptions = Sbubscription.all
  end

  # GET /sbubscriptions/1
  # GET /sbubscriptions/1.json
  def show
  end

  # GET /sbubscriptions/new
  def new
    @sbubscription = Sbubscription.new
  end

  # GET /sbubscriptions/1/edit
  def edit
  end

  # POST /sbubscriptions
  # POST /sbubscriptions.json
  def create
    @sbubscription = Sbubscription.new(sbubscription_params)

    respond_to do |format|
      if @sbubscription.save
        format.html { redirect_to @sbubscription, notice: 'Sbubscription was successfully created.' }
        format.json { render :show, status: :created, location: @sbubscription }
      else
        format.html { render :new }
        format.json { render json: @sbubscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sbubscriptions/1
  # PATCH/PUT /sbubscriptions/1.json
  def update
    respond_to do |format|
      if @sbubscription.update(sbubscription_params)
        format.html { redirect_to @sbubscription, notice: 'Sbubscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @sbubscription }
      else
        format.html { render :edit }
        format.json { render json: @sbubscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sbubscriptions/1
  # DELETE /sbubscriptions/1.json
  def destroy
    @sbubscription.destroy
    respond_to do |format|
      format.html { redirect_to sbubscriptions_url, notice: 'Sbubscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sbubscription
      @sbubscription = Sbubscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sbubscription_params
      params.require(:sbubscription).permit(:name)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end
  
  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    token= Stripe::Token.create({
      card: {
        number: params[:card_number],
        exp_month: params[:card_month],
        exp_year: params[:card_year],
        cvc: params[:card_code],
      },
    })
    if @subscription.save_with_payment(token)
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Invalid Request Error: #{e.message}"
    redirect_to @subscription, :notice => "Invalid Request, TRY AGAIN!"
    false
  rescue Stripe::CardError => e
    logger.error "Card Error: #{e.message}"
    redirect_to @subscription, :notice => "Card Error, TRY AGAIN!"
    false
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:name, :email, :card_number, :card_code, :card_month, :card_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sbubscriptions_helper.rb
module SbubscriptionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscriptions</title>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
  <%= yield %>

  <%= javascript_include_tag "https://js.stripe.com/v3/", "application" %>
</body>
</html>

app/views/sbubscriptions/_form.html.erb
<%= form_with(model: sbubscription, local: true) do |form| %>
  <% if sbubscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sbubscription.errors.count, "error") %> prohibited this sbubscription from being saved:</h2>

      <ul>
      <% sbubscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sbubscriptions/edit.html.erb
<h1>Editing Sbubscription</h1>

<%= render 'form', sbubscription: @sbubscription %>

<%= link_to 'Show', @sbubscription %> |
<%= link_to 'Back', sbubscriptions_path %>

app/views/sbubscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sbubscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sbubscriptions.each do |sbubscription| %>
      <tr>
        <td><%= sbubscription.name %></td>
        <td><%= link_to 'Show', sbubscription %></td>
        <td><%= link_to 'Edit', edit_sbubscription_path(sbubscription) %></td>
        <td><%= link_to 'Destroy', sbubscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sbubscription', new_sbubscription_path %>

app/views/sbubscriptions/new.html.erb
<h1>New Sbubscription</h1>

<%= render 'form', sbubscription: @sbubscription %>

<%= link_to 'Back', sbubscriptions_path %>

app/views/sbubscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sbubscription.name %>
</p>

<%= link_to 'Edit', edit_sbubscription_path(@sbubscription) %> |
<%= link_to 'Back', sbubscriptions_path %>

app/views/subscriptions/_form.html.erb
<%= form_with(model: @subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<%= form_for @subscription do |f| %>
  <% if @subscription.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>  
  <div class="field">
      <%= label_tag :card_number, "Credit Card Number " %>
      <%= text_field_tag :card_number, nil, name: 'card_number' %>
  </div>
  <div class="field">
      <%= label_tag :card_code, "Security Code on Card (CVV)" %>
      <%= text_field_tag :card_code, nil, name: 'card_code' %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers_true: true}, {name: 'card_month', id: "card_month"}%>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: 'card_year', id: "card_year"}%>
  </div>
  <div class="actions"><%= f.submit "Subscribe" %></div>
<% end %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>